### ISSUE TITLE
Feature Request QuickMenu

### ISSUE THREAD

**Issue by maladro1t** [Odyseus/CinnamonTools#1]
Hey there, Well done! I like this applet very much!
I want to make a kind of mate-menu and i work with sub-folders (e.g. Applications with the sub-folders office and Media. Is it possible to give any sub-folder its own icon? 
I really would love this.

Thank you!

**Comment by Odyseus** [comment]
Hello, maladro1t.

I considered that feature while I was developing this applet. But I didn't find a way to do it without using an external file to save the menu layout. And I want to avoid doing that at all cost. I want to keep this applet as close as possible to the functionality of the XFCE plugin called **Directory Menu** and the KDE (or Plasma or whatever it is called now a days that thing) widget called **Quick Access**.

I have in mind a way of achieving custom icons for the sub-menus. It would require to create a .directory file in each folder that will be used to create a sub-menu. But I still have to try it out. This weekend I will start working on that.

**Comment by Odyseus** [comment]
Hello, maladro1t.

I managed to implement your requested feature. I didn't do it like I commented in my previous message. I chose to do it using just one manually created file instead of one for each folder. This way, everything can be found in none place. Plus, hard drive reads are also reduced.

I also added a couple more features that I had in mind (custom icon sizes, items styling from the settings window instead of the stylesheet.css file, etc). You can read more in detail on this applet [Spices website](https://cinnamon-spices.linuxmint.com/applets/view/260).

**Comment by maladro1t** [comment]
Hey Odyseus, great news. I will have a look als soon as i can.  

Greetz

--  
maladro1t@yahoo.com
