### ISSUE TITLE
Layout of custom launchers and application info boxes

### ISSUE THREAD

**Issue by sphh** [Odyseus/CinnamonTools#12]
Hi,

Thank you for the better menu!! I finally can get rid of the favourites, but I also like all the other options.

Would it be possible to add some configuration possibilities regarding the layout of the "Custom Launcher" and the "Application Info" boxes? I find it distracting that I have to glance over the "Custom Launcher" box to see the application info, so I would love to have the "Application Info" box above the "Custom Launcher", but to have them side by side might be also a viable option.

Yes, I now that I can display the info in a tooltip, but there is a considerable lag and the "Application Info" box looks so much neater!

Thank you for your consideration!

Stephan

**Comment by Odyseus** [comment]
Hello, @sphh.

When I first introduced the "Custom Launchers" box into my menu, I was in doubt where to place it with respect to the info box. I had the same doubt about the position of the "Custom Launchers" box and the Search box when both are placed to the bottom of the menu.

Now that you have brought to my attention this feature request, it just occurred to me how to "fine tune" the position of all elements in the menu. Stay tuned for the next release.

**Comment by Odyseus** [comment]
Hello, @sphh.

I uploaded a "developer edition" of the Custom Cinnamon Menu applet for testing purposes. It can be installed alongside the normal version without interfering with each other. You will see it as **Custom Cinnamon Menu DEV** inside the applets manager.

I had to redesign some parts of the applets settings due to the *change on the logic* of the menu layout. There is a new section on the settings page called **Menu layout** where the elements of the menu can be shown/hidden and reordered.

As the "info box" can now be placed in any part of the menu and I couldn't make the top/bottom padding for this box to work right, elements surrounding this box will need to have some padding set (from the **Appearance** section on the settings window).

Let me know if you test it and find some issues and/or if the settings names needs to be re-worded.

**Comment by sphh** [comment]
Hi,

Sorry for the late answer. I was away ...

Today I wanted to install the **TEST** version, but cannot find it in the applets manager. I am curious!

**Comment by Odyseus** [comment]
Hello, @sphh.

Sorry for not being more specific. I didn't upload it to the Spices website, I upload it into this repository. You will have to download this repository and install the "test" applet manually. And then the applet will be available on the applets manager.

**Comment by Odyseus** [comment]
Hello, @sphh.

I already implemented your request on this issue. I uploaded to this repository the version 1.17 of this applet. I will wait a couple of days before uploading this version to Spices so I can see if there are any errors. Then everyone can update it from the applets manager.

I also updated the "test" version on this repository. This version is exactly the same as the "normal" version but it can be installed alongside the normal version without interfering with each other.

**Comment by sphh** [comment]
Hi,

Yesterday I managed to install the TEST version. It works on my computer and I like the idea and implementation. Thanks!!

There were only two flaws:
1. When I first started it, the custom launcher with the shutdown button was missing. This was easily rectify, but might cause irritation by a new user.
2. I cannot get rid of the "Add to favourites" context sensitive menu.

Should I open new bugs for these two issues?

Many thanks again!
Stephan

**Comment by Odyseus** [comment]
Hello, @sphh.

1. Yes, I forgot to place the custom launchers box at the end of the menu as a default.
2. I initially didn't add an option to hide the **Add/Remove to/from Favorites** context menu. Mainly to avoid confusion. Because not everyone knows that a Favorite can be added/removed by just drag and drop. In addition, if you hide the Favorites box and you activate the favorites category, without the context menu, you will loose the ability to add/remove favorites because the favorites category doesn't have drag and drop capabilities.

> Should I open new bugs for these two issues?

There is no need to open new issues because:
- I already set the custom launchers box as default on initial install.
- I already added drag and drop capabilities for when the Favorites box is hidden and also added an option to hide the **Add/Remove to/from Favorites** context menu.

I will have ready an updated TEST version for today or tomorrow in case that you want to give it another try.

Thank you very much for your feedback, Stephan.

:+1:
