### ISSUE TITLE
Simple ToDo List:Show count of pending tasks

### ISSUE THREAD

**Issue by danleyb2** [Odyseus/CinnamonTools#123]
How can i configure the count of tasks in the bar (value in brackets) to only count pending tasks, 
I checkbox to mark what is done, 
I know i can remove the done tasks to get the right count but i still want to keep them for reference

**Comment by Odyseus** [comment]
Hello, @danleyb2.

In it's current state, you can't configure the applet to achieve that behavior.

I realize now that having the count of total tasks in the applet label is not very useful. I think that, even adding something like `(4/10)` (4 tasks completed out of a total of 10 tasks) is not very useful for someone that has more than one tasks list either.

I was thinking of adding a tooltip with detailed information about all tasks and their completed state. But that would be kind of redundant too, because it's as easy to open the menu to see that exact same information, and the menu is easier to open (and to keep open) than a tooltip.

The code that allows to display the amount of tasks if currently very complex. But I will see if something can be done to display the total amount of tasks and the completed number of tasks (for example, `(4/10)`). Would that be something that approaches to what you want to achieve?

**Comment by danleyb2** [comment]
@Odyseus 

yes, something like (4/10) would be better since you can then see per task list on click

**Comment by Odyseus** [comment]
Hello, @danleyb2.

I implemented the feature discussed in this issue and the one discussed in your other issue (#124). You can test it by manually updating the applet [downloaded from this repository](https://odyseus.github.io/CinnamonTools/pkg/0dyseus@SimpleToDoList.tar.gz).
