### ISSUE TITLE
Simple ToDo List:Pasted task gets truncated if longer than width

### ISSUE THREAD

**Issue by danleyb2** [Odyseus/CinnamonTools#124]
Steps to reproduce the issue

1. Click ToDo
2. Click a task list (e.g **Tasks list - Some examples**) drop-down to add a new task
3. Paste this
> this is a very long text that i tried to paste as a new task but it got truncated and the rest i had to type

the pasted result on my [system](https://gist.github.com/anonymous/46a204e2fad82007d992469ca1cb1831)  was
> this is a very long text that i tried to paste as a new task but it got tru

**Comment by Odyseus** [comment]
Hello, @danleyb2.

What you describe is the normal behavior of the **New task...** entry. This entry doesn't have the same characteristics that an already created task entry has. The **New task...** entry cannot wrap its text nor it can have multiple lines and the limit of characters isn't defined by the menu width, but by a constant defined on the code itself ([75 characters](https://github.com/Odyseus/CinnamonTools/blob/master/applets/0dyseus%40SimpleToDoList/files/0dyseus%40SimpleToDoList/__init__.js#L22)). This was inherited from the Gnome Shell extensions from which i based this applet.

I think that I will remove such behavior and add the features of the task entries to the **New task...** entry. It doesn't make sense having such limits when a task entry *"can do whatever it wants"*.

**Comment by danleyb2** [comment]
@Odyseus the pasted works okay now, though the input seems to have a fixed height that doesn't resize,
editing the second line of a long task gets a little difficult, this is how it looks

![screenshot from 2017-06-19 23-47-40](https://user-images.githubusercontent.com/9919961/27316960-00ec6c72-558c-11e7-8ccf-90fa7e258717.png)

**Comment by Odyseus** [comment]
Hello, @danleyb2.

Please, read the applet help file (accessed from the applet context menu). It specifies who is the culprit of that behavior and how to fix it.

**Comment by Odyseus** [comment]
@danleyb2: I just discovered a *formatting error* on the help file for the **Simple ToDo List** applet, so you might not find very easily the section were that issue is described. I already fixed it, but if you don't want to update the entire applet just to get the updated help file, you can just consult the [on-line help file for this applet](https://odyseus.github.io/CinnamonTools/help_files/0dyseus@SimpleToDoList.html). The section that will be of interest to you is **Known issues** > **Task entries look wrong**.
