### ISSUE TITLE
Argos: ruby script with require line displays nothing

### ISSUE THREAD

**Issue by edaubert** [Odyseus/CinnamonTools#128]
### Description

I try to use the plugin `Argos for Cinnamon` with a ruby script.
This script has a `require` line (`require 'gitlab'`).
The script runs well in a terminal but when it is assign to the plugin, nothing is displayed.
If I use another script without the `require` lines, everything is fine.
Have you already tried a script with some `require` lines ?
In addition, I use chruby to define my ruby environment (ruby 2.4.1)

### Steps to reproduce

1. write a ruby script with a require
2. use the script with Argos

**Expected behavior:** Display what you want (even a simple hello world)
**Actual behavior:** Display nothing
**Reproduces how often:** Always

### System information
```bash
$ inxi -xxxSc0 -! 31
System:    Kernel: 4.8.0-58-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.4.4 (Gtk 3.18.9-1ubuntu3.3) dm: mdm Distro: Linux Mint 18.2 Sonya
```

### System logs
https://gist.github.com/edaubert/02dfc22577a7a647712e190d3b3fa8ea
https://gist.github.com/fe2369b8abb4c6205f1d318db881e13b

**Comment by Odyseus** [comment]
Hello, @edaubert.

Argos for Cinnamon doesn't care what the script you assign to it does, as long as the script prints to output a valid string that can be parsed by the applet.

I'm not very familiar with the ruby language, but if you see the **python_examples.py** script that comes with the applet (the one used by default when an instance of the applet is placed on a panel), scripts can be as complex as one needs them to be. The **python_examples.py** script has imports and even a function declared and called to create the example menu.

Without a practical example of a ruby script I cannot be of much help. Provide a script that has a `require` entry in it and describe what do you expect the applet to look like after the script has finished execution (what should the applet display in the panel and if it should generate menu entries or not).

**Comment by edaubert** [comment]
Hello,

Thanks for your answer.

I found that my dependencies were not resolved.
I am looking for a fix for this.

Meanwhile concerning Argos, is it be possible to add a log for error output ?
Indeed to find my issue, I need to add some logs and I update a function in `init.js`

I did it here: https://github.com/edaubert/cinnamon-spices-applets/blob/argosforcinnamon/0dyseus%40ArgosForCinnamon/files/0dyseus%40ArgosForCinnamon/__init__.js#L2275

I added the code below while I commented `GLib.close(stderrFile);`

```javascript

    let standardError = '';

    let stderrStream = new Gio.DataInputStream({
        base_stream: new Gio.UnixInputStream({
            fd: stderrFile
        })
    });

    readStream(stderrStream, function (error) {
        if (error === null) {
            stderrStream.close(null);
            global.logError(standardError);
        } else {
            standardError += error;
        }
```

**Comment by Odyseus** [comment]
Hello, @edaubert.

> I found that my dependencies were not resolved. I am looking for a fix for this.

Again, if you want me to make precise tests, you will have to provide an example script. Although, I use a completely different Ruby environment ([rbenv](https://github.com/rbenv/rbenv)).

> Meanwhile concerning Argos, is it be possible to add a log for error output ?

Well, I simply test my Argos scripts on a terminal before using them on an instance of an applet. But *an extra layer of logging* doesn't hurt. In addition, the shell in a terminal and the shell used by the applet to execute scripts might have completely different contexts, so the logging of the **stderr** output might be needed in such a cases.

But I will make that logging conditional. As you have it set up, it will *pollute* the `glass.log` file with empty error lines.

Since it turned out your problem wasn't an Argos bug (apparently), I will close this issue for now. I can re-open it if you find out that indeed is an Argos bug. Just let me know.

Thank you very much for your feedback. :+1:
