### ISSUE TITLE
No menu items in QuickMenu

### ISSUE THREAD

**Issue by sphh** [Odyseus/CinnamonTools#16]
On a fresh Linux Mint 18.1 installation I added QuickMenu via "Add applets to the panel". I switched the directory ("Choose main directory") to `$HOME/QuickMenu`, closed the configuration window, updated the menu with right click>"Update menu", but the menu is empty. I only get an empty blackish box of the size of menu item. The folder `$HOME/QuickMenu` contains two .desktop files, no other files and no subfolders.

If there is any way to help to track down this problem, I am happy to do so!

**Comment by Odyseus** [comment]
Hello, sphh.

I couldn't reproduce your issue in my setup of Linux Mint 18.1 until I changed the main directory from the settings window.

I found the problem and I seem to have fixed it. The problem is that in Cinnamon 3.2.x, the directory selector in the settings windows return an URI, not a path.

I uploaded a new version of the applet that should fix your issue. Let me know if everything works as it should.

Thank you very much for your feedback. 👍

**Comment by sphh** [comment]
Thanks. I updated the files manually and it's working now. Great!!

BTW I noticed that you deleted the `_tryToGetValidIcon` function, but there is still a reference to it. I guess, that was intentional, but to be on the safe side, I did not delete it. Does that make any difference?

**Comment by Odyseus** [comment]
I deleted the **_tryToGetValidIcon** function from the **MyApplet** prototype because in the last version I moved its declaration and usage into the **FileMenuItem** prototype. So, you can delete it without any issues. Just copy the entire content of the **applet.js** file in this repo into the one located inside the **3.2** folder of your local applet and you will be golden.

**Comment by sphh** [comment]
You are right. I should have looked further down in the file. Thanks for the quick response!!
