### ISSUE TITLE
Disappearing contents in Custom Cinnamon Menu's configuration window

### ISSUE THREAD

**Issue by sphh** [Odyseus/CinnamonTools#17]
I noticed the following somewhat strange behaviour:

1. Open the configuration window by right-clicking on the Menu and select "Configure...".
2. Select the "Appearance" tab.
3. Scroll down to the bottom by dragging the slider.
4. Select the "Applet" tab.
5. The content area is empty (at least on my screen).

**Comment by Odyseus** [comment]
Hello, @sphh.

Since the moment that you click on **Configure** and the settings window is opened, you will see the vertical scrollbar to the right of the window. That's because all *tabs* on the settings window are inside the same scroll view. When you went into the **Appearance** tab and scrolled all the way down, you also scrolled all the way down in all other tabs. When you go back to the **Applet** tab, you have to scroll all the way up to see its content. It isn't a *problem* with the applet itself, it's how the new settings system creates its windows.

I could **fix it** by simply creating more tabs and re-distribute the content of the tabs with large data (like the **Appearance** and **Custom commands** tabs), but that would create another problem. When there are too much tabs in a settings window that will occupy more space than the window width allows, the entire tabs section disappears. That's another problem with the new settings system.

The base problem here is that the settings system on Cinnamon is designed for simple layouts/configurations. I'm *demanding* too much of if by creating the large amount of settings this applet has (136 settings to be precise).

**Comment by sphh** [comment]
Hello @Odyseus,

Thank you for the explanation. Actually I thought it might had to do with Cinnamon handling this window.

What was even more puzzling, is the fact, that the new scroll bars disappear if the mouse does not hover over it. This gives absolutely no clue that there might be more in the hiding.

Does it make sense to file a bug against Cinnamon's setting windows?

**Comment by Odyseus** [comment]
I don't think that it is needed to report these issues to Cinnamon. Like I said, the settings system isn't designed to handle such large amount of data. But if you thing that it is worth it, go ahead.

**About the scrollbars:** Those hidden scrollbars are a *feature* added by the *geniuses* of Gnome developers. You can disable that stupidity from **System Settings** > **Effects**. Uncheck the option called **Overlay scrollbars (logout required)**. Then log out and back in, and the scrollbars will be visible as they should.

You will still see that the programs launched as root will still have those repugnant auto-hidden scrollbars. You can get rid of those too by simply adding to the **/etc/environment** file this: `GTK_OVERLAY_SCROLLING=0`. No need to log out this time, just close and re-open the applications opened as root that have the scrollbars auto-hidden.
