### ISSUE TITLE
Popup Translator bug and translation 

### ISSUE THREAD

**Issue by NikoKrause** [Odyseus/CinnamonTools#19]
Hey,

the Popup Translator seems a little bit buggy. When I left click on it, there appears a blank popup menu, which does not dissapear (just restarting Cinnamon helps).
![screenshot-area-2017-01-20-161426](https://cloud.githubusercontent.com/assets/8415124/22154383/93fb279c-df2b-11e6-9964-70b459a26c35.png)

But I can translate, when marking a text, pressing the Popup-Applet and then reloading the history.

The history window is not translated, "Source text", "Reload", etc.

Here is a German translation.
[po.zip](https://github.com/Odyseus/CinnamonTools/files/719728/po.zip)

I also updated the template.pot file and updated es.po against the template with poeditor.

Since I also translated the languages, they are no longer alphabetically ordered in the settings dropdown menu. Don't know if this can be fixed.

**Comment by NikoKrause** [comment]
Also you could do the following:
```js
        menuItem.connect("activate", Lang.bind(this, function() {
            Util.spawn(["xdg-open", this.main_applet_dir + "/" + _("HELP.md")]);
        }));
```

Make "HELP.md" translatable. Thus the translator has the opportunity to translate it for example to "HELP_es.md", then create a file with this name and save the Spanish (es) translation of HELP.md in this file.

**Comment by Odyseus** [comment]
Hello, @NikoKrause.

Let's go by parts, said Jack the Ripper. LOL

**Important note:** I will tell you this here so you don't waste your time troubleshooting. The **applet.js** file found in the root of the applet directory and the one found inside the **3.2** folder should be identical, but they aren't. Plus, the **settings-schema.json** file inside the **3.2** folder wasn't updated to event make it work with the changes that I made. So, for now, it's better that you remove and uninstall the applet until I update it. Since I already removed it from Spices, check out the one in my repositories (**not updated yet**).

Yes, the Popup Translator applet is very buggy because it's in beta stage. I uploaded it into Spices just to test the publishing of new applets and I already deleted it just to test the deletion of applets. It was part of a test in which I created a pull request with the updates of all my applets, just to keep the reviewers on their toes. LOL

> When I left click on it, there appears a blank popup menu, which does not dissapear (just restarting Cinnamon helps).

When you first place the applet on the panel, it checks if all dependencies are met. If there are any dependencies missing, a popup notification will appear informing you of that and that you should see the **~/.cinnamon/glass.log** file for details. Are you sure that it was a *"real empty popup"* and not an empty notification popup? It couldn't have been a *"real empty popup"* because the applet can't show an empty popup (I put in place some *safe guards* to avoid showing the popup when there isn't any selected text). And if the popup was in fact an empty notification popup, that would be an error on the applet's side, because the notification should be shown only if there is something to show. The fact that it stays visible when you click elsewhere it's because it's a *critical* notification popup.

> The history window is not translated, "Source text", "Reload", etc.

Not done yet. In the makings.

> Since I also translated the languages, they are no longer alphabetically ordered in the settings dropdown menu. Don't know if this can be fixed.

The languages weren't meant to be translated precisely because the breaking of the alphabetical order. What happens is that in the extraction of strings from the **settings-schema.json** isn't selective (it's all or nothing), so the list of languages are extracted and put in the .pot file. There isn't a fix for it as far as I know.

> Maybe you could add a "Clear history" button to the translation history?

I want to avoid at all cost the clearing of the translation history, mainly to avoid the abuse of the translation services, so I will not be adding a **Clear history** button. But I will add something similar. I plan to add a context menu item that will open the folder were the translation history is stored (it's stored inside a .json file). This way, the file can be removed or renamed and the history will be cleared. I still didn't test this very well.

> And maybe also a panel icon. When the applet is added first, it is invisible, since there is no icon and no default text.

There is an icon for the applet. Something must have prevented the correct initialization of the applet when you first placed it into the panel. Remember to **ALWAYS** look at the **~/.cinnamon/glass.log** file for errors. That's the first thing that you should look after placing into the panel any applet that gives you an error.

> Make "HELP.md" translatable.

I was thinking of doing this for all my applets, but I still didn't find a mechanism good enough to implement it. What you propose doesn't convince me too much. Plus, I am constantly editing/correcting the help files of my newer applets, so it will be a nightmare to keep the translated file in sync with the original. I will keep this in mind for the future.

**Comment by NikoKrause** [comment]
> Are you sure that it was a "real empty popup" and not an empty notification popup?

I mean it looks like the screenshot in my first post.

I haven't used the applet from spices, but from your repo to translate it.

**Comment by NikoKrause** [comment]
> > Make "HELP.md" translatable.

> I was thinking of doing this for all my applets, but I still didn't find a mechanism good enough to implement it. What you propose doesn't convince me too much. Plus, I am constantly editing/correcting the help files of my newer applets, so it will be a nightmare to keep the translated file in sync with the original. I will keep this in mind for the future.

I don't know if it's practical. Maybe you could write a script, which extracts each line in the HELP.md file and wraps it with 
```
msgid "Line1"
msgstr ""

msgid "Line1"
msgstr ""
```

E.g. `md2pot HELP.md`. And an option to revert the process `md2pot -i`. E.g. the script would grab each msgstr line by line from "ES.po" and would create a "HELP_ES.md" file.

**Comment by Odyseus** [comment]
Hello, @NikoKrause.

I just updated the Popup Translator applet. It's totally functional now when installed on Cinnamon 3.2.x. Still not tested on Cinnamon 2.8.x.

You can download the package directly from [this link](https://odyseus.github.io/CinnamonTools/pkg/0dyseus@PopupTranslator.zip). In the main README of this repository I added direct downloads to packaged applets/extensions/themes (easier for manual installations).

**About HELP.md files translations:** The proposed solution in your last comment is indeed unpractical. I liked more [your first proposal](https://github.com/Odyseus/CinnamonTools/issues/19#issuecomment-274101427). I already have something in mind to implement it in the future.

**Comment by NikoKrause** [comment]
Here's an updated translation:
[de.po.zip](https://github.com/Odyseus/CinnamonTools/files/749991/de.po.zip)
