### ISSUE TITLE
[Feature request] Peek at Window, when hover over thumbnail in window-list applet

### ISSUE THREAD

**Issue by NikoKrause** [Odyseus/CinnamonTools#2]
Hey,

could you add a feature, which lets you peek at the Window, when you hover over the thumbnail.
I mean, you get a thumbnail (small preview) of a window, when you hover over the window-list applet.
Now when you hover over this thumbnail, it should show the Window, i.e. the other windows should go transparent.

This feature is already implemented in this applet: 
https://cinnamon-spices.linuxmint.com/applets/view/16

But I would like it to have this feature in your applet, because I'm not a big fan of grouping windows.

**Comment by Odyseus** [comment]
Hello, NikoKrause.

I will see want I can do. If it's easy to implement, I will add that feature to my applet.

**Comment by NikoKrause** [comment]
Thanks for your effort.

**Comment by NikoKrause** [comment]
@Odyseus 
I have a question about the contextMenu in the menu-applet.
If I right click on an application the contectMenu opens at the bottom.
Do you know, if there is a way to make it open at the top of the button istead?

**Comment by Odyseus** [comment]
Hello, @NikoKrause.

Mmmm. I don't think so. The context menus are instances of **PopupSubMenu**, and those elements doesn't have the possibility to set an orientation like the **PopupMenu** elements do.

**Comment by NikoKrause** [comment]
And you don't think PopupMenu can be used instead?

**Comment by Odyseus** [comment]
> And you don't think PopupMenu can be used instead?

I don't think/know so. A **PopupMenu** element is a menu that pops up from its target. A **PopupSubMenu** element is an in-line menu *attached* to its target. But I could be wrong.

**Comment by Odyseus** [comment]
Hello, @NikoKrause.

I recently updated the window list applet. I simply re-based it on the window list applet that comes with Cinnamon 3.2 and added some more options. But sadly, I'm gonna have to give up on this feature request. It turned out to be too complicated. Mainly because the **WindowPreview** prototype of the original window list applet (the one that creates the windows thumbnails) is an instance of the **Tooltips** prototype. All of the applets that use a window thumbnail that can be hovered uses an instance of the **PopupMenu** prototype to create the windows thumbnails. If I add a **CustomWindowPreview** prototype based on the **PopupMenu** prototype, I would have to re-write a lot of the existent code to handle the show/hide of the **CustomWindowPreview**. This isn't needed for the default **WindowPreview** because a tooltip naturally hides/shows itself, saving a lot of code.

If in the future I find a simpler way to implement this feature, I will surely try to add it again.

:+1:

**Comment by Odyseus** [comment]
@NikoKrause.

I forgot to comment on this. There is a new applet called [Icing Task Manager](https://cinnamon-spices.linuxmint.com/applets/view/269) and is based on the one that you linked on your first message. It seems to work a lot better and the app grouping can be disabled.

**Comment by NikoKrause** [comment]
Thanks for your effort.
Here is a German Translation of Custom Cinnamon Menu as a little Thank you for always helping me out:
[de.po.zip](https://github.com/Odyseus/CinnamonTools/files/644733/de.po.zip)

**Comment by Odyseus** [comment]
Thank you very much for the translation, @NikoKrause!!! Adding it right now.

Would it be too much to ask if you could update the German translation for the [Window list applet](https://github.com/Odyseus/CinnamonTools/blob/master/Applets/0dyseus%40window-list-fork/po/de.po)? I could have done it myself, but I don't want to *"insult"* your native language by using Google Translator (LOL). There are only 9 new strings. You could just post the translated strings in here if you prefer.

**Comment by NikoKrause** [comment]
Yes. I'll update the translation. That's no problem.
