### ISSUE TITLE
Czech translation for Popup Translator applet 

### ISSUE THREAD

**Issue by Radek71** [Odyseus/CinnamonTools#21]
[0dyseus@PopupTranslator.po.zip](https://github.com/Odyseus/CinnamonTools/files/731609/0dyseus.PopupTranslator.po.zip)
Notes:
- list of languages is not translated
- some strings are not extracted to .pot file (for example Powered by...) and are not translated.
- some strings are translated to Czech, but are ignored by applet ( Choose a key bindings...). Could you check it please?

**Comment by Odyseus** [comment]
Hello, @Radek71.

Thanks again for your contribution.

As you can see, the Popup Translator applet is still a prototype (alpha stage), so I would advice you to wait before creating the .po file for this applet.

The language list isn't meant to be translated. This is because that list is used to create a **combobox** entry in the settings window. That setting is ordered alphabetically using the language names in English. If the languages are all translated, the alphabetical order would break, because the **combobox** entry is created following the order defined in the **settings-schema.json** file. I'm still looking for a way to fix this, but I not very hopeful.

> some strings are not extracted to .pot file (for example Powered by...) and are not translated.

Fixed in next prototype version.

> some strings are translated to Czech, but are ignored by applet ( Choose a key bindings...).

The only things that occurs to me is that you are using a very old version of Cinnamon 3.2.x which doesn't have a mechanism to translate the settings window strings. Or you forgot to uninstall a previous version of your translation and update it with the newer version. I checked your .po file and all seems to be OK without any errors, so the translation should work.

**Comment by Radek71** [comment]
Hello, @Odyseus 

seems that you changed this applet from prototype to initial release. I have updated Czech translation, but I would like to ask you for adding these strings to .pot file:
Source language
Target language
(G) = Language supported...
(Y) = Language supported...

**Comment by Odyseus** [comment]
Hello, @Radek71.

That's right, I already released the applet into Spices yesterday.

I already fixed the missing strings on the .pot file on the applet uploaded in this repository. It should be ready to be translated now. Read [this line](https://github.com/Odyseus/CinnamonTools/blob/master/applets/0dyseus%40PopupTranslator/files/0dyseus%40PopupTranslator/applet.js#L102) on the applet's code for information about this.

Thanks. 👍

**Comment by Radek71** [comment]
Hello, @Odyseus 

thanks. Updated Czech translation is attached.
[0dyseus@PopupTranslator.po.zip](https://github.com/Odyseus/CinnamonTools/files/749620/0dyseus.PopupTranslator.po.zip)

**Comment by Radek71** [comment]
@Odyseus 

updated Czech translation for v1.05
[0dyseus@PopupTranslator.po.zip](https://github.com/Odyseus/CinnamonTools/files/983730/0dyseus.PopupTranslator.po.zip)

**Comment by Radek71** [comment]
@Odyseus 

updated Czech translation for v1.05
[0dyseus@PopupTranslator.po.zip](https://github.com/Odyseus/CinnamonTools/files/1034814/0dyseus.PopupTranslator.po.zip)

A piece of cosmetic :-):
- **Second translation mechanism ([[Ctrl]] + Middle click):** Same as [[Ctrl]] + Left click.
should be formatted as
- **Second translation mechanism ([[Ctrl]] + Middle click):** Same as [[Ctrl]] + **Left click**.

**Comment by Odyseus** [comment]
> A piece of cosmetic...

Fixed and uploaded. Thanks again, @Radek71. 👍

**Comment by Radek71** [comment]
@Odyseus 

updated Czech translation for v1.05
[0dyseus@PopupTranslator.po.zip](https://github.com/Odyseus/CinnamonTools/files/1059914/0dyseus.PopupTranslator.po.zip)

**Comment by Radek71** [comment]
@Odyseus 

updated czech translation for 1.06 is attached
[0dyseus@PopupTranslator.po.zip](https://github.com/Odyseus/CinnamonTools/files/1122930/0dyseus.PopupTranslator.po.zip)
