### ISSUE TITLE
Popup Translator: Secondary Language

### ISSUE THREAD

**Issue by sphh** [Odyseus/CinnamonTools#23]
Hi,

A couple of days ago I had this idea that a quick translating tool living in the panel would be nice and voilà it arrived just in time. Thanks!!!!

Would it be possible to add another target language?

My motivation behind is:
I'm not an English native speaker, so I want most of the translation done into my mother tongue. But sometimes I have to write in English, so I want to translate words into English.

This could be implemented by clicking with the middle mouse button?

Thanks for considering this.

**Comment by Odyseus** [comment]
Hello, @sphh.

> Would it be possible to add another target language?

That's a thing that I had in mind when I started developing this applet, although, in a different way. I had planed for the popup to show more than one translation at the same time (from different services and/or with different language pairs). I discarded the idea because too much requests to the service providers could trigger an *abuse* of the services (Read this applet help file **About translation history** section for details on what I'm talking about).

I'm reluctant to add a middle click option to this applet (or any of my applets). Mainly because there are in existence hardware that doesn't have a middle click (mediocre laptops, for example). Nut I will start to disregard this and completely ignore mediocre hardware all together.

I have in mind a method that could, in some way, fulfill your request. I'm thinking of adding more configurable hotkeys. And on each hotkey one can configure the service provider and the language pair. This will allow us to have at our finger tips different configurations without the need to open the applet's settings window.

**Comment by sphh** [comment]
Thank you for considering this and answering it!

There could be a Ctrl+mouse click for these poor souls without a middle mouse button.

I personally not so much a fan of only-hotkeys-options. I love hotkeys, when I have my hands on the keyboard, so that I don't have to move my hand to the mouse. On the other hand, when I select some text to be translated (e.g. when surfing), I don't want to move my hand to the keyboard. That's why I prefer to have both keyboard and mouse options.

I'm not sure if that helps in you decision...

**Comment by Odyseus** [comment]
> There could be a Ctrl+mouse click for these poor souls without a middle mouse button.

The Ctrl + left click already has the function of performing a forced translation. What I'm thinking on doing is the following:

- Left click on applet: Translate using the **primary** language.
- Ctrl + Left click on applet: Forced translation using the **primary** language.
- Middle click on applet: Translate using the **secondary** language.
- Ctrl + Middle click on applet: Forced translation using the **secondary** language.

Those that doesn't have middle click available can use hotkeys or buy a freaking mouse (LOL).

> I personally not so much a fan of only-hotkeys-options.

I'm not a fan of hotkeys neither. That's why I always create hotkeys that can be accessed with just one hand (my left hand).

But I'm still deciding how to implement all this changes. We will see how it goes.

**Comment by sphh** [comment]
Hi!

Thanks. I'm looking forward how you will finally implement it!

**Comment by Odyseus** [comment]
Hello, @sphh.

I created a test version of the Popup Translator applet.

What's new:
- It has 4 different *translation mechanisms* (Left click, Middle click, Hotkey 1 and Hotkey 2). 
- Each *translation mechanisms* can have it's own individual service providers, language pairs and hotkeys.

It can be downloaded from the link at the end of this message. It can be installed along with your already installed version and will have its own settings and translation history. You will see it on the Applets Manager with the name **Popup Translator (Test)**.

[0dyseus@PopupTranslatorTest.tar.gz](https://github.com/Odyseus/CinnamonTools/files/765204/0dyseus.PopupTranslatorTest.tar.gz)

**Comment by sphh** [comment]
Hello @Odyseus,

Thanks. I just installed it and notice two things:

1. A type: "Hoykey" in the configuration screen.
2. I removed **Popup Translator** after adding **Popup Translator (Test)** to the panel and _both_ applets were removed from the panel. (This should not effect the final version.)

I had a couple of other ideas regarding the middle click: It would still be great to have a way to call the second translation without middle click (I own one of those laptops... Even if I can produce a middle click by 3 fingers, the exact location is far from reliably determinable). What about using Shift+Mouse click? Or Alt+Mouse click?

Another option would be to allow multiple applets to be added (is that even possible with Cinnamon). Each instance would have a different translation. With a custom icon it would be even possible to identify the language.

Just some thought...

I already like your new version!

**Comment by Odyseus** [comment]
Hello, @sphh

> A type: "Hoykey" in the configuration screen.

If I would have released the applet with that typo, the translators would have hated me! LOL

> I removed Popup Translator after adding Popup Translator (Test) to the panel and both applets were removed from the panel. (This should not effect the final version.)

That's kind of impossible. Both applets (the test version and the stable version) have completely different UUIDs. Plus, both versions have "infinite" multi-instances enabled (it means that you can already place into your panels several versions of either applet at the same time).

My guess is that you must have installed a version of Popup Translator from this repository from when it was still a prototype. Or installed it from the Spices website the very first day that the new design came on-line. If so, those versions were very buggy and you should remove them and also remove their configuration files (~/.cinnamon/configs/0dyseus@PopupTranslator/0dyseus@PopupTranslator.json). These earlier versions didn't have the ability to be added more than once into your panels.

> What about using Shift+Mouse click? Or Alt+Mouse click?

I wanted to avoid that. I have [experience creating custom buttons](http://custombuttons.sourceforge.net/forum/search.php?keywords=&terms=all&author=Odyseus&fid%5B%5D=4&sc=1&sf=titleonly&sr=topics&sk=t&sd=d&st=0&ch=300&t=0&submit=Search) for a Firefox add-on called [Custom Buttons](https://addons.mozilla.org/en-US/firefox/addon/custom-buttons/?src=search). Some of my buttons can be configured to use all modifier keys in conjunction with any of the three mouse buttons. The mechanism to implement that isn't that complex. But in practice, In addition to have a very complex configuration system, I found myself always looking at the tooltips to see what the heck this or that hotkey actually does.

I think that, with the ability to add more that one instance of the applet into any panel and, in addition, the ability to create custom hotkeys, we have several configuration options without so much complexity.

Thanks for the feedback, sphh! :+1:

I updated the applet attached to my previous message. It just have the "Hoykey" typo fixed.

**Comment by sphh** [comment]
Hi @Odyseus 

Thank you for your explanations.

Did you notice my typo when complaining about yours??

Yes, you might be right, that I installed the Popup Translator as soon as it came out.

Since it's now possible to add two instances of the translator applet, all that discussion about secondary languages, mouse button modifiers etc becomes somewhat obsolete. (I have not checked, if it also can sport different configurations...) Just mention it in the documentation and most of the people should be happy.

One more issue I noticed: I changed the configuration of the applet, but the tooltip did not get updated.

**Comment by sphh** [comment]
I just double-checked: Now the tooltip is updated. Maybe the following happened: I added another instance. I moved the mouse over one of the two instances and found the default tooltip. I believe it was the first and customized instance. I opened the configuration dialog and it showed the customized values. Then I closed the dialog. Now the tooltip is updated.

I might have got the two instances mixed up (or maybe not). Honestly I can't remember, so please forget my comment about the tooltip not updating.

**Comment by Odyseus** [comment]
> Did you notice my typo when complaining about yours??

Are you referring to you using the word "type" instead of "typo"? If so, yes. LOL

> Just mention it in the documentation and most of the people should be happy.

Do not worry about that. The HELP.md file in the new version will be updated reflecting the new changes. This is just a test version. As you can see, I also removed the **po** folder, so the translators that may be reading this issue do not waste their time translating strings that most likely will contain errors, as you pointed out.

About the tooltips.

- If you are on Cinnamon 3.0.7, it's easy to mix the settings page for applets with several instances. You have to constantly hit the **Highlight** button to keep track of them.
- If you are on Cinnamon 3.2.x it's easier to keep track of the setting page for the applets, because the applet it's highlighted, but the themes has to support such highlighting. Plus, if you restart Cinnamon with the settings window opened, the highlighting is "lost".

If you find more issues about this, just let me know. But specify which exact setting were you trying to change.

It is worth mentioning that the **Hotkey #1** and **Hotkey #2** will not be displayed in the tooltip until you actually set a keybinding for them. Also, the "quick provider selection" on the applet context menu will not automatically appear/hide when enabling/disabling these two settings until Cinnamon is restarted. I still can't find a way to update the context menu without rebuilding it from scratch. So I might have to add a note somewhere about a Cinnamon restart needed.

**Comment by Odyseus** [comment]
Hello, @sphh.

I finished implementing the new feature proposed for this applet in this issue, along with several changes and improvements.

#### Changelog

- Fixed keybindings not registered on applet initialization.
- Implemented 4 different translation mechanisms that will allow to have various translation options at hand without the need to constantly change the applet settings. Read the HELP.md file for more details (It can be accessed from this applet context menu).
- Re-designed the translation history mechanism to be *smarter*. Now, if, for example, a string is translated into four different languages, the strings will be stored into four different entries in the translation history.
- Moved some of the context menu entries into a sub-menu.
- Removed unused import from appletHelper.py file.
- Added new icons to the icons folder that represent the translation services used by this applet.
- Added debugging options to facilitate development.
- Added LICENSE.md file to applet.

I already uploaded the new version into this repository. Attached to this message you will find a test version. Both versions are exactly the same, just with different UUIDs and names. Use the one from the repository only on a *test environment*. It is not recommended to install the one from the repository until I upload it to the Spices website.

[0dyseus@PopupTranslatorTest.tar.gz](https://github.com/Odyseus/CinnamonTools/files/769074/0dyseus.PopupTranslatorTest.tar.gz)


@NikoKrause & @Radek71

The localization files of the new version of Popup Translator applet will need to be updated. I would suggest you to wait for a couple of days in case that I find errors that need to be corrected.

👍

**Comment by sphh** [comment]
Hi @Odyseus !

Thank you so much! I do like it.

I just found two minor issues:

1. When selecting the help option, the HELP.md file opens in my text editor (the default xed) and all the beautiful formatting is lost.
2. The about dialog looks funny: 
![screenshot from 2017-02-12 13-24-04](https://cloud.githubusercontent.com/assets/4856462/22862474/f988a8f2-f126-11e6-91f8-1f3ec92519bb.png)

**Comment by Odyseus** [comment]
Hello, @sphh.

1. Mmm. I don't have that problem. I can see the syntax highlighting for that file with xed and with my prefered editor (Sublime Text).

![screenshot from 2017-02-12 19-09-32](https://cloud.githubusercontent.com/assets/3822556/22866603/115667cc-f158-11e6-9339-8ef9f2d4048c.png)

![screenshot from 2017-02-12 19-09-24](https://cloud.githubusercontent.com/assets/3822556/22866602/1119fc06-f158-11e6-95a1-936f1ac0e16e.png)


2. If by funny you mean all text overflows, then is your theme's fault. The about dialog isn't *flexible*, it has hard-coded sizes and when the content doesn't fit, it overflows the elements boundaries. That's why I edited the about dialogs of the two themes that I have in this repository with the sizes of the about dialog used in the Mint-Y themes.

- **Before**:

![Before image](https://odyseus.github.io/CinnamonTools/lib/img/About-Dialog-Size-Before.png "Before image")

- **After**:

![After image](https://odyseus.github.io/CinnamonTools/lib/img/About-Dialog-Size-After.png "After image")

**Comment by sphh** [comment]
Hi @Odyseus ,

1. Yes, the help file does show with syntax highlighting. I was more thinking along the line how texts in markdown language should be finally displayed, such as the `README.md` file in github. Most likely it's not worth the effort! Maybe opening the webpage on the spices website?
2. I thought that it might not be your "fault", still I thought you might be interested. And yes, by "funny" I mean the overflowing text. BTW I still use the old Mint-X theme...

**Comment by Odyseus** [comment]
> I was more thinking along the line how texts in markdown language should be finally displayed, such as the README.md file in github.

Oh. You meant that, when the Help item on context menu is pressed, it should display its content rendered into a web page and not the markdown file.

Well, that's something that I did in my first applets. I had the HELP.md file and the HELP.html file inside the applet folder. The Help item on the context menu opened the HELP.html file and the HELP.md file was there just as a source to create the HRLP.html file. But I fed up with the need to rebuild the HTML file every time that I updated the HELP.md file. Plus, it required to ship the applet with a folder that contained CSS styles to render correctly the web page (or worse, add in-line the CSS code into the HTML file manually). I simply dimmed all that work not worthy.

I also investigated the use of scripts that would render a markup file on the fly and display it in a browser. But all of them have dependencies that not all system may have installed. And adding a dependency to the applet just to display its help file isn't very smart, to say the least.

I decided to use a markdown file simply because, now a days, every text editor that deserves to be called as such has markdown syntax highlighting. And some text editors even have markdown rendering capabilities (Sublime Text, Atom, ).

**Comment by NikoKrause** [comment]
Another option would be instead of opening the HELP.md file, you could make it open the website
https://github.com/linuxmint/cinnamon-spices-applets/blob/master/0dyseus%40PopupTranslator/files/0dyseus%40PopupTranslator/HELP.md

**Comment by Odyseus** [comment]
Hello, @NikoKrause.

That is not an option. The help for any software should always be available off-line, no exceptions.

@All

I updated the Popup Translator applet again. I will repeat my previous instructions because they are important to take into account.

Attached to this message you will find a test version. Both versions are exactly the same, just with different UUIDs and names. Use the one from the repository only on a *test environment*. It is not recommended to install the one from the repository until I upload it to the Spices website.

### Changelog

- Re-designed the translation history window. Now, only one instance of the history window can be opened at the same time. Removed **Reload** button in favor of auto-update of the history window content every time the translation history changes and the translation window is open.

[0dyseus@PopupTranslatorTest.tar.gz](https://github.com/Odyseus/CinnamonTools/files/770736/0dyseus.PopupTranslatorTest.tar.gz)

**Comment by Odyseus** [comment]
Hello, everybody.

@sphh: Just to keep you (and anybody reading) in the loop. I found a new method that will allow me to create a translator applet that will support 4 different translation services (Google, Yandex, Bing and Apertium). It will force me to create a completely new applet, but with a lot more options (like text-to-speech) and will have a totally different approach than the Popup Translator has.

Right now is all *just in my head*. When I have a functional applet ready to test, I will open a new issue for beta testing and feedback.

@NikoKrause & @Radek71

The Popup Translator applet from this repository is stable enough and ready to publish on Spices. I will wait for your updated localization files before publishing it. No hurry though. The one published is pretty stable and the only bug it has isn't critical. Thanks in advance, guys. :+1:

**Comment by NikoKrause** [comment]
@Odyseus 
[de.po.zip](https://github.com/Odyseus/CinnamonTools/files/785936/de.po.zip)

I hope I catched the right version

**Comment by Radek71** [comment]
@Odyseus 
[0dyseus@PopupTranslatorTest.po.zip](https://github.com/Odyseus/CinnamonTools/files/786155/0dyseus.PopupTranslatorTest.po.zip)

**Comment by Odyseus** [comment]
@NikoKrause and @Radek71.

I will have to bother you with something. I had to make some last minute changes and I had to change two strings that will need to be updated.

#### Old strings:

```
Read the HELP.md file (Help item on this applet context menu) found inside this applet folder to know how to get free Yandex API keys.
```

```
Check this applet HELP.md file for instructions.
```

#### New strings:

```
Read the help file (Help item on this applet context menu) found inside this applet folder to know how to get free Yandex API keys.
```

```
Check this applet help file for instructions.
```

No need for creating the .po file again. Just post a comment here with the translated strings when you have some time.

Thanks again and sorry for the trouble, guys.

**Comment by Radek71** [comment]
@Odyseus 
Přečtěte soubor s nápovědou (položka Nápověda v kontextovém menu tohoto apletu), který je umístěn ve složce tohoto apletu s popisem jak získat  Yandex API klíče.

Zkontrolujte soubor s nápovědou tohoto apletu pro získání instrukcí.
