### ISSUE TITLE
Custom Cinnamon Menu

### ISSUE THREAD

**Issue by muzena** [Odyseus/CinnamonTools#28]
@Odyseus 

Can you add options in Custom Cinnamon Menu to on/off or show/hide items in Menu, for items from Cinnamon Control Center?

**Comment by Odyseus** [comment]
Hello, @muzena.

I don't see this happening. You can already do that with Cinnamon Menu Editor. For what I could see on the Cinnamon Menu Editor code, its implementation is tied entirely to the application UI. Which means that I can't directly access the Python code from the applet's JavaScript code. This observation is based in a very superficial examination of the Cinnamon Menu Editor code.

But you can already hide any menu item by simply using the **Edit .desktop file** on the applications context menu. You just have to open it, save a copy into **~/.local/share/applications** and change or add **NoDisplay=true**. Done. The menu will automatically refresh and the menu item will be hidden. All of this is what the Cinnamon Menu Editor does in essence.

Adding a mechanism to perform these tasks directly by the menu is kind of useless. Because you can only hide menu items from the menu itself, not un-hide them. And to un-hide them, you will have to use either the Cinnamon Menu Editor or delete the files manually from **~/.local/share/applications**.
