### ISSUE TITLE
Exstensions manager applet

### ISSUE THREAD

**Issue by muzena** [Odyseus/CinnamonTools#75]
Exstensions manager applet doesn't lists extensions.
.xsession.errors:

(cinnamon:2882): Cjs-WARNING **: JS ERROR: Exception in callback for signal: destroy: Error: No signal connection undefined found
_disconnect@resource:///org/cinnamon/cjs/modules/signals.js:76:11
PopupMenuBase.prototype._connectItemSignals/<@/usr/share/cinnamon/js/ui/popupMenu.js:1869:17
_emit@resource:///org/cinnamon/cjs/modules/signals.js:142:27
PopupBaseMenuItem.prototype.destroy@/usr/share/cinnamon/js/ui/popupMenu.js:208:9
PopupMenuBase.prototype.removeAll@/usr/share/cinnamon/js/ui/popupMenu.js:2052:13
MyApplet.prototype._populateSubMenus/this._populateSubMenusId<@/home/goran/.local/share/cinnamon/applets/0dyseus@ExtensionsManager/applet.js:345:17

**Comment by Odyseus** [comment]
Hello, @muzena.

I cannot reproduce you problem. I have all extensions installed in my Cinnamon 3.4 system and all of them are shown on the Extensions Manager applet menu.

That error that you posted is produced by the call to **this.menu.removeAll();** in line 345 of the applet.js file. I also have that error in my .xsession.errors. The error itself isn't in the applet, but in Cinnamon. Why is that error triggered? I have no idea. If you ask me, CJS 3.8 is more annoying than useful.

That part of the code is there to inform you that you don't have extensions installed or that you need to update the menu manually. Do the following:

1. Go to the extensions manager and update the list of on-line extensions.
2. Restart Cinnamon.
3. Extensions Manager applet menu should then have listed all your installed extensions categorized by Enabled/Disabled.

**Comment by muzena** [comment]
I also have Cinnamon 3.4.
I try all of these steps, I completely remove and then install Extensions manager, update the list, restart Cinnamon.


Instead of extension list, there is message:
There aren't any extensions installed on your system. Or you may need to refresh the list of extensions from this applet context menu.

**Comment by Odyseus** [comment]
> 1. Go to the extensions manager and update the list of on-line extensions.

This first step is important. I'm not referring to the **Refresh extensions list** item on the Extensions Manager applet context menu. Go to **System Settings** > **Extensions** > **Available extensions (on-line)** > press **Refresh list** button. When it **successfully finishes**, restart Cinnamon.

**Comment by muzena** [comment]
I have last version of extension manager but don't work.
On Cinnamon 3.2 work, on Cinnamon 3.4 dosen't work.

**Comment by Odyseus** [comment]
@muzena.

Go to **~/.local/share/cinnamon/applets/0dyseus@ExtensionsManager** and check if the file called **appletHelper.py** is set as executable. I it isn't, set it as executable and restart Cinnamon.

If your problem persists, open a terminal inside the applet folder and run the command `./appletHelper.py --list`. The output of that command should be a JSON *object* with all your installed extensions in it. You can upload it to a Gist and post the URL here for me to inspect. BE AWARE!!! That JSON *object* contains the absolute paths of all your extensions. You can do a search/replace to change the path to your home to **~/**.

**Comment by muzena** [comment]
@Odyseus 
https://gist.github.com/muzena/f73041731c855872bb455ca74b2bf621

**Comment by Odyseus** [comment]
@muzena.

Now I can see what is happening! Remove the extension CinnaDockPlus@entelechy and restart Cinnamon. That should do the trick.

What is happening is that when the **appletHelper.py** script is executed by the applet to get the list of extensions, that error message is returned along with the JSON *object*. When the applet tries to parse that string, it fails because is not a valid JSON *object*.

The rare thing is that I have installed the CinnaDockPlus@entelechy extension and it doesn't throw any error.

I will have to tweak the **appletHelper.py** script to return a "sanitized" JSON *object*. I have no idea how to do that, though. LOL

I will also have to log the error into the glass.log file. Because we would have found the error a lot sooner if I would just added that.

Please, let me know if removing the CinnaDockPlus@entelechy extension fixes your problem. In case it doesn't, run again the command `./appletHelper.py --list` to see if it reports any other error.

**Comment by muzena** [comment]
Yes, after removing CinnaDockPlus and reinstalling Exstensions manager it works.
These two CinnaDock extensions also don't work, they are broken.
