### ISSUE TITLE
Window List applet doesn't start on Cinnamon 3.4.1

### ISSUE THREAD

**Issue by seigneurfuo** [Odyseus/CinnamonTools#97]
### Description

Window List applet doesn't start on Cinnamon 3.4.1

### Steps to reproduce

1. Just log-in and waiting for Cinnamon desktop to be loaded

**Expected behavior:** Normal execution

**Actual behavior:** The applet doesn't starts

**Reproduces how often:** 100%, every cinnamon lauchs

### System information

System:    Kernel: 4.10.17-2-MANJARO x86_64 (64 bit gcc: 6.3.1)
           Desktop: Cinnamon 3.4.1 (Gtk 3.22.15) dm: lightdm
           Distro: Manjaro Linux

### System logs

https://pastebin.com/mNW6Kt31
https://pastebin.com/RsT1X13T

**Comment by Odyseus** [comment]
Hello, @seigneurfuo.

I cannot reproduce your issue. The applet loads and works fine for me on Linux Mint with Cinnamon 3.4.x installed. Sadly, I can't test the applet on a system similar to yours because I don't use Manjaro and Archlinux is still installing Cinnamon 3.2.8, not 3.4.x.

I see no errors on either of your log files. The **0dyseus@window-list-fork** applet seems to load fine and the logs are perfectly clean.

I have a couple of suggestions/questions.

- Are you using the applet installed from the Spices website or from this repository? If you are using the one from the Spices website, [try the one on this repository](https://odyseus.github.io/CinnamonTools/pkg/0dyseus@window-list-fork.tar.gz). It has a couple of fixes, although, none of then are fatal.
- Try removing the default **menu@cinnamon.org** applet. I don't think that they can't interfere with each other (in fact, in my 3.4.x system I have both, the default and my fork placed in different panels), but just in case.
- Try a clean install. Remove the folders `~/.local/share/cinnamon/applets/0dyseus@window-list-fork` and `~/.cinnamon/configs/0dyseus@window-list-fork`, install the version of the applet that I linked above and then restart Cinnamon.
- If you can, post a screenshot of your desktop with a couple of windows opened.

**Comment by seigneurfuo** [comment]
It works ! Using the last version from this repository and clean install the applet. No more errors. Thank you.

**Comment by Odyseus** [comment]
Hello, @seigneurfuo.

Glad that it works for you.

> Is the applet will be updated on Cinnamon Spice Website in the future ?

Yes, I periodically update all my xlets in the Spices repository. In fact, today was *update day* for me and I updated all my applets on the Spices repository. So, currently, all of my applets published on the Spices website are *in sync* with the ones on this repository.
